package com.sws.code.mycode.entity;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.enabled
     *
     * @mbg.generated
     */
    private Integer enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbg.generated
     */
    private Integer city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.county
     *
     * @mbg.generated
     */
    private Integer county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.area
     *
     * @mbg.generated
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.resident
     *
     * @mbg.generated
     */
    private Integer resident;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.long_itude
     *
     * @mbg.generated
     */
    private Double longItude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lat_itude
     *
     * @mbg.generated
     */
    private Double latItude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.agency_name
     *
     * @mbg.generated
     */
    private String agencyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.owner_id
     *
     * @mbg.generated
     */
    private Integer ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account
     *
     * @return the value of user.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account
     *
     * @param account the value for user.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.enabled
     *
     * @return the value of user.enabled
     *
     * @mbg.generated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.enabled
     *
     * @param enabled the value for user.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createtime
     *
     * @return the value of user.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createtime
     *
     * @param createtime the value for user.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbg.generated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbg.generated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.county
     *
     * @return the value of user.county
     *
     * @mbg.generated
     */
    public Integer getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.county
     *
     * @param county the value for user.county
     *
     * @mbg.generated
     */
    public void setCounty(Integer county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.area
     *
     * @return the value of user.area
     *
     * @mbg.generated
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.area
     *
     * @param area the value for user.area
     *
     * @mbg.generated
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.resident
     *
     * @return the value of user.resident
     *
     * @mbg.generated
     */
    public Integer getResident() {
        return resident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.resident
     *
     * @param resident the value for user.resident
     *
     * @mbg.generated
     */
    public void setResident(Integer resident) {
        this.resident = resident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.type
     *
     * @return the value of user.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.type
     *
     * @param type the value for user.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.long_itude
     *
     * @return the value of user.long_itude
     *
     * @mbg.generated
     */
    public Double getLongItude() {
        return longItude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.long_itude
     *
     * @param longItude the value for user.long_itude
     *
     * @mbg.generated
     */
    public void setLongItude(Double longItude) {
        this.longItude = longItude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lat_itude
     *
     * @return the value of user.lat_itude
     *
     * @mbg.generated
     */
    public Double getLatItude() {
        return latItude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lat_itude
     *
     * @param latItude the value for user.lat_itude
     *
     * @mbg.generated
     */
    public void setLatItude(Double latItude) {
        this.latItude = latItude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.agency_name
     *
     * @return the value of user.agency_name
     *
     * @mbg.generated
     */
    public String getAgencyName() {
        return agencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.agency_name
     *
     * @param agencyName the value for user.agency_name
     *
     * @mbg.generated
     */
    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName == null ? null : agencyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.owner_id
     *
     * @return the value of user.owner_id
     *
     * @mbg.generated
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.owner_id
     *
     * @param ownerId the value for user.owner_id
     *
     * @mbg.generated
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", account=").append(account);
        sb.append(", phone=").append(phone);
        sb.append(", password=").append(password);
        sb.append(", enabled=").append(enabled);
        sb.append(", createtime=").append(createtime);
        sb.append(", city=").append(city);
        sb.append(", county=").append(county);
        sb.append(", area=").append(area);
        sb.append(", resident=").append(resident);
        sb.append(", type=").append(type);
        sb.append(", address=").append(address);
        sb.append(", longItude=").append(longItude);
        sb.append(", latItude=").append(latItude);
        sb.append(", agencyName=").append(agencyName);
        sb.append(", ownerId=").append(ownerId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}